version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: server
    container_name: web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
networks:
  mynetwork:
    driver : bridge